# Generated by Django 4.2.6 on 2025-07-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TraduccionVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etiquetas.idioma')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traducciones', to='etiquetas.variable')),
            ],
            options={
                'unique_together': {('variable', 'idioma')},
            },
        ),
    ]
