# Generated by Django 4.2.6 on 2025-07-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0002_idioma_variable_traduccionvariable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idioma',
            name='id',
        ),
        migrations.AlterField(
            model_name='idioma',
            name='codigo',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
