# Generated by Django 4.2.6 on 2025-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0003_remove_idioma_id_alter_idioma_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='default',
            field=models.CharField(default='sin valor', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='descripcion',
            field=models.CharField(default='sin valor', max_length=255),
            preserve_default=False,
        ),
    ]
