# Generated by Django 4.2.6 on 2025-07-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0004_variable_default_variable_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.IntegerField()),
                ('base_url', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tamanio', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rotacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('angulo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='tipo_etiqueta',
            field=models.CharField(choices=[('Rotulo Interno', 'Rotulo Interno'), ('Etiqueta Externa', 'Etiqueta Externa')], default='Rotulo interno', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='impresora',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etiquetas.impresora'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='insumo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etiquetas.insumo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiqueta',
            name='rotacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etiquetas.rotacion'),
            preserve_default=False,
        ),
    ]
