# Generated by Django 4.2.6 on 2025-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0005_impresora_insumo_rotacion_etiqueta_tipo_etiqueta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='dpi',
            field=models.CharField(max_length=10),
        ),
    ]
