# Generated by Django 4.2.6 on 2025-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0006_alter_impresora_dpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='dpi',
            field=models.IntegerField(),
        ),
    ]
