# Generated by Django 4.2.6 on 2025-07-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0007_alter_impresora_dpi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impresora',
            old_name='base_url',
            new_name='descripcion',
        ),
    ]
