# Generated by Django 4.2.6 on 2025-07-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0008_rename_base_url_impresora_descripcion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='etiqueta',
            constraint=models.UniqueConstraint(fields=('tipo_etiqueta', 'nombre'), name='unique_nombre_por_tipo'),
        ),
    ]
