# Generated by Django 4.2.6 on 2025-07-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etiquetas', '0009_etiqueta_unique_nombre_por_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='idioma',
            field=models.ForeignKey(default='ES', on_delete=django.db.models.deletion.CASCADE, to='etiquetas.idioma'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='codigo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variable',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='variable',
            constraint=models.UniqueConstraint(fields=('codigo', 'idioma'), name='unique_variable_por_idioma'),
        ),
    ]
